### ISSUE TITLE
porter下ZKClusterNodeListen监听问题

### ISSUE THREAD

**Issue by aipan** [sxfad/porter#3]
package cn.vbill.middleware.porter.cluster.zookeeper;
ZKClusterNodeListener监听问题
//下发命令
if (NODE_ORDER_PATTERN.matcher(zkEvent.getPath()).matches()) {
  NodeCommandConfig commandConfig = JSONObject.parseObject(zkEvent.getData(), NodeCommandConfig.class); 
  ...
  //删除指令
   client.delete(zkEvent.getPath());
}
这里监听后，执行删除指令后又继续监听，zkEvent.getData()为null。造成
集群节点监听->/porter/node/1/order/fd41270e-622e-4048-b73a-4b0e1750b0c6,null,OFFLINE
java.lang.NullPointerException: null

是否应改为
//下发命令
 if (NODE_ORDER_PATTERN.matcher(zkEvent.getPath()).matches() && zkEvent.isOnline()) {

**Comment by zhangkewei** [comment]
是的。如果可以，欢迎帮助优化代码，修复发现的BUG.
