### ISSUE TITLE
AlerterFactory关闭线程池

### ISSUE THREAD

**Issue by aipan** [sxfad/porter#7]
check方法中：
 CyclicBarrier barrier = new CyclicBarrier(stats.size() + 1);
创建了stats.size() + 1屏障
但是只创建线程池，线程数量为3
//创建线程池
            int threadSize = 3;
            ExecutorService service = Executors.newFixedThreadPool(threadSize);

            for (DTaskStat stat : stats) {
                service.submit(new Runnable() {
                    @Override
                    public void run() {
                        //执行任务
                        try {
                            alerter.check(dataConsumer, dataLoader, stat, getCheckMeta(work, stat.getSchema(), stat.getTable()), work.getReceivers());
                        } finally {
                            try {
                                barrier.await();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    }
                });
            }
分配告警检查任务到线程池子中，提交3个任务后，barrier.await();就在等待了，该任务没结束，然后线程池不能继续提交剩下的代码，所以导致线程卡在这。

**Comment by zhangkewei** [comment]
首先说声抱歉。
按照当前的业务逻辑，确实是您理解的样子。当时的本意是大于5张表的检查就通过线程池执行，单元测试未覆盖大于五张表的检查，生产环境也没基于各方面的原因没有使用该功能，以至于问题没有被发现。修复代码稍后提交。

**Comment by zhangkewei** [comment]
已修复。
